"""Change filename column again due to text length

Revision ID: 43154a330299
Revises: 8f51d836548c
Create Date: 2026-02-07 23:00:12.675293

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "43154a330299"
down_revision: Union[str, Sequence[str], None] = "8f51d836548c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("uploaded_files", "filename", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("uploaded_files", "filename", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False)
    # ### end Alembic commands ###
