"""Create question-chunk table for HyPE implementation

Revision ID: 2fdd5778ec5a
Revises: e87bec764bd0
Create Date: 2026-02-10 23:17:36.793700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2fdd5778ec5a"
down_revision: Union[str, Sequence[str], None] = "e87bec764bd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_chunk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_uuid", sa.UUID(), nullable=True),
        sa.Column("chunk_uuid", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id", "question_uuid", "chunk_uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question_chunk")
    # ### end Alembic commands ###
