"""Add size of file column

Revision ID: 3c37b00bd52e
Revises: 43154a330299
Create Date: 2026-02-08 11:51:59.911031

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3c37b00bd52e"
down_revision: Union[str, Sequence[str], None] = "43154a330299"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("uploaded_files", sa.Column("size", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploaded_files", "size")
    # ### end Alembic commands ###
