"""Удалил таблицу Question_chunk

Revision ID: 954ad4fd8edf
Revises: 2fdd5778ec5a
Create Date: 2026-02-13 22:38:20.633209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "954ad4fd8edf"
down_revision: Union[str, Sequence[str], None] = "2fdd5778ec5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question_chunk")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_chunk",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("question_uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("chunk_uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", "question_uuid", "chunk_uuid", name=op.f("question_chunk_pkey")),
    )
    # ### end Alembic commands ###
