"""Change filename column type

Revision ID: 8f51d836548c
Revises: 39511d592e0f
Create Date: 2026-02-07 22:59:08.751800

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8f51d836548c"
down_revision: Union[str, Sequence[str], None] = "39511d592e0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("uploaded_files", "filename", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("uploaded_files", "filename", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False)
    # ### end Alembic commands ###
