"""Change id type due to Qdrant connection

Revision ID: e87bec764bd0
Revises: 3c37b00bd52e
Create Date: 2026-02-08 14:41:00.344402

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e87bec764bd0"
down_revision: Union[str, Sequence[str], None] = "3c37b00bd52e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("uploaded_files", sa.Column("qdrant_file_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploaded_files", "qdrant_file_id")
    # ### end Alembic commands ###
